services:
  frontend:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  backend:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development