name: saper

services:
  server:
    container_name: saper-server
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 8085
      LOG_LEVEL: ${SERVER_LOG_LEVEL:-info}
    ports:
      - "8085:8085"

  client:
    container_name: saper-client
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        VITE_WS_URL: wss://saper.majorkow.ski/ws
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "8084:80"
